### ISSUE TITLE
Hello, how does one install this plugin? | Ciao, come si fa a settare questo plugin?

### ISSUE THREAD

**Issue by pilino** [randallarms/gunsmith#23]
(**Original**, _Italian_)
ma, come si fa a settare questo plugin

(_English_)
but, how do you set this plugin

(_Spanish_)
pero, como instalo esto plugin?

**Comment by randallarms** [comment]
**Italian response**: 

Per installare questo plugin per Minecraft, visitare [questa pagina](https://www.spigotmc.org/resources/gunsmith.31040/) e cliccare su "Download Now" vicino alla parte superiore. Quindi aggiungere il file scaricato nella cartella "plugins" del server e caricare il server. I comandi sono elencati nella pagina che ho citato sopra. Buona fortuna!

**English response:** 

To install this plugin for Minecraft, visit [this page](https://www.spigotmc.org/resources/gunsmith.31040/) and click "Download Now" near to the top. Then add the downloaded file to your server's "plugins" folder and load your server. The commands are listed on the page I mentioned above. Good luck!

**Comment by randallarms** [comment]
- Closes #23
