### ISSUE TITLE
ResoucePack block error !

### ISSUE THREAD

**Issue by Zaohon** [randallarms/gunsmith#43]
It is seems that the lava block is blank .
i am running bukkit 1.11.2 and use "GunSmithPackV3" resouce pack

**Comment by randallarms** [comment]
Was this issue resolved properly? If so, can you tell me what was wrong? Thanks!

EDIT: Also, please note that the resource pack is for Minecraft version 1.12+.
EDIT no.2: Please be sure to "star" and "watch" this repository on GitHub to stay up-to-date with all changes!
